apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        # fsGroup: 1000 
        runAsUser: 0 
      serviceAccountName: jenkins-admin
      containers:
        - name: jenkins
          image: "514095112279.dkr.ecr.eu-central-1.amazonaws.com/jenkins_docker:1.7.1"
          resources:
            limits:
              memory: "1000Mi" 
              cpu: "500m"
            requests:
              memory: "1000Mi" 
              cpu: "500m"
          ports:
            - name: httpport
              containerPort: 8080
            - name: jnlpport
              containerPort: 50000
          livenessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: "/login"
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: jenkins-data
              mountPath: /var/jenkins_home         
            - name: docker-socket
              mountPath: /var/run/docker.sock
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
            claimName: jenkins-home-claim
        # - name: jenkins-home
        #   gcePersistentDisk:
        #     pdName: jenkins-home
        #     fsType: ext4
        #     partition: 1
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: File

---

apiVersion: v1
kind: Service
metadata:
  namespace: jenkins
  name: jenkins
  labels:
    app: jenkins
spec:
  type: ClusterIP
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: slave
      port: 50000
      protocol: TCP
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: jenkins