apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: main-vpc
  labels:
    name: main-vpc
spec:
  forProvider:
    region: eu-central-1
    cidrBlock: 10.10.0.0/16
    enableDnsSupport: true
    enableDnsHostNames: true
  providerConfigRef:
    name: aws-provider-config